
services:
  mysql:
    image: mysql:8.0
    container_name: expense-calculator-local
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: expense_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - .data/db:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3
    tty: true
